import { createPortal } from "react-dom";
import { Printer, X } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import type { Language } from "@/contexts/UserModeContext";
import type { ContractResult, RevisionSuggestion } from "@/lib/featherlessAI";

interface RevisionReportProps {
  result: ContractResult;
  onClose: () => void;
  language?: Language;
  variant?: "revision" | "regulator";
}

function buildFallbackSuggestions(result: ContractResult): RevisionSuggestion[] {
  if (result.revisionSuggestions?.length) {
    return result.revisionSuggestions;
  }

  return (result.redFlags ?? []).map((flag, index) => ({
    clauseNumber: `Issue ${index + 1}`,
    clauseName: "Potential concern",
    originalText: result.clauseQuote || flag,
    issue: flag,
    suggestedRevision: result.clauseTranslation || "Ask the provider to rewrite this clause in plain language before signing.",
    legalBasis: result.riskReason || "Requires human review before acceptance.",
  }));
}

export function RevisionReport({
  result,
  onClose,
  language = "en",
  variant = "revision",
}: RevisionReportProps) {
  const today = new Intl.DateTimeFormat(language === "zh" ? "zh-CN" : "en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  }).format(new Date());

  const suggestions = buildFallbackSuggestions(result);
  const copy =
    language === "zh"
      ? {
          title: variant === "regulator" ? "潜在掠夺性借贷报告" : "合同修订建议报告",
          subtitle:
            variant === "regulator"
              ? "用于向导师、评委或监管方解释为什么这份合同结构值得进一步调查。"
              : "用于在签署前和对方逐条讨论风险条款与修改建议。",
          risk: "风险等级",
          summary: "摘要",
          reasoning: "系统解释",
          suggestions: variant === "regulator" ? "潜在违规点" : "修订建议",
          original: "原文",
          issue: variant === "regulator" ? "问题说明" : "风险说明",
          fix: variant === "regulator" ? "建议行动" : "建议改写",
          basis: variant === "regulator" ? "为什么需要升级处理" : "法律或合规依据",
          checklist: variant === "regulator" ? "升级处理清单" : "签署前核对清单",
          footer: "本报告由 FinClear 生成，仅供风险沟通与教育演示使用，不构成正式法律意见。",
          print: "打印 / 导出 PDF",
        }
      : {
          title: variant === "regulator" ? "Potential Predatory Lending Report" : "Contract Revision Report",
          subtitle:
            variant === "regulator"
              ? "Use this to explain to judges, mentors, or regulators why the structure deserves closer review."
              : "Use this before signing to negotiate risky clauses and proposed revisions.",
          risk: "Risk Level",
          summary: "Summary",
          reasoning: "System Reasoning",
          suggestions: variant === "regulator" ? "Potential Violations" : "Revision Suggestions",
          original: "Original",
          issue: variant === "regulator" ? "Observed issue" : "Why it matters",
          fix: variant === "regulator" ? "Suggested action" : "Suggested rewrite",
          basis: variant === "regulator" ? "Escalation basis" : "Legal / compliance basis",
          checklist: variant === "regulator" ? "Escalation Checklist" : "Pre-sign Checklist",
          footer: "This report was generated by FinClear for risk communication and educational use. It is not formal legal advice.",
          print: "Print / Export PDF",
        };

  const riskTone =
    result.riskLevel?.includes("High") || result.riskLevel?.includes("高")
      ? "text-red-600"
      : result.riskLevel?.includes("Medium") || result.riskLevel?.includes("中")
        ? "text-amber-600"
        : "text-emerald-600";

  if (typeof document === "undefined") return null;

  return createPortal(
    <div className="fixed inset-0 z-[100] overflow-y-auto bg-black/70 py-8 backdrop-blur-sm">
      <div className="print:hidden fixed right-4 top-4 z-[101] flex gap-2">
        <Button type="button" className="rounded-full" onClick={() => window.print()}>
          <Printer data-icon="inline-start" />
          {copy.print}
        </Button>
        <Button type="button" variant="outline" size="icon" className="rounded-full bg-white dark:bg-[#0B0F19]" onClick={onClose}>
          <X />
        </Button>
      </div>

      <div
        className="mx-auto w-full max-w-[210mm] bg-white text-black shadow-2xl print:max-w-none print:shadow-none"
        style={{ fontFamily: "'Noto Serif SC', 'Songti SC', serif" }}
      >
        <div className="flex items-start justify-between gap-6 px-10 pb-8 pt-10">
          <div>
            <p className="text-xs uppercase tracking-[0.3em] text-slate-400">FinClear</p>
            <h1 className="mt-3 text-3xl font-bold tracking-wide">{copy.title}</h1>
            <p className="mt-3 max-w-2xl text-sm leading-relaxed text-slate-600">{copy.subtitle}</p>
          </div>
          <div className="text-right text-xs text-slate-500">
            <p>{today}</p>
            <p className="mt-2">ID: FC-{Date.now().toString(36).toUpperCase()}</p>
          </div>
        </div>

        <Separator className="bg-slate-200" />

        <div className="grid gap-6 px-10 py-8 md:grid-cols-[0.95fr_1.05fr]">
          <div className="rounded-2xl bg-slate-50 p-6">
            <p className="text-xs uppercase tracking-[0.3em] text-slate-400">{copy.risk}</p>
            <p className={`mt-3 text-xl font-bold ${riskTone}`}>{result.riskLevel}</p>
            <p className="mt-3 text-sm leading-relaxed text-slate-700">{result.riskReason}</p>
          </div>

          <div className="rounded-2xl bg-slate-50 p-6">
            <p className="text-xs uppercase tracking-[0.3em] text-slate-400">{copy.reasoning}</p>
            <p className="mt-3 text-sm leading-relaxed text-slate-700">{result.transparentReasoning}</p>
          </div>
        </div>

        <Separator className="bg-slate-200" />

        <div className="px-10 py-8">
          <h2 className="text-lg font-bold">{copy.suggestions}</h2>
          <div className="mt-6 flex flex-col gap-5">
            {suggestions.map((suggestion, index) => (
              <div key={`${suggestion.clauseNumber}-${index}`} className="rounded-2xl border border-slate-200 p-5">
                <div className="flex flex-wrap items-center justify-between gap-3">
                  <h3 className="text-base font-bold">
                    {suggestion.clauseNumber} · {suggestion.clauseName}
                  </h3>
                  <span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">
                    {copy.summary} {index + 1}
                  </span>
                </div>

                <div className="mt-5 grid gap-4 md:grid-cols-2">
                  <div>
                    <p className="text-[11px] font-semibold uppercase tracking-[0.25em] text-slate-400">{copy.original}</p>
                    <p className="mt-2 rounded-xl bg-red-50 p-4 text-sm leading-relaxed text-slate-700">{suggestion.originalText}</p>
                  </div>
                  <div>
                    <p className="text-[11px] font-semibold uppercase tracking-[0.25em] text-slate-400">{copy.issue}</p>
                    <p className="mt-2 rounded-xl bg-amber-50 p-4 text-sm leading-relaxed text-slate-700">{suggestion.issue}</p>
                  </div>
                </div>

                <div className="mt-4 grid gap-4 md:grid-cols-2">
                  <div>
                    <p className="text-[11px] font-semibold uppercase tracking-[0.25em] text-slate-400">{copy.fix}</p>
                    <p className="mt-2 rounded-xl bg-emerald-50 p-4 text-sm leading-relaxed text-slate-700">{suggestion.suggestedRevision}</p>
                  </div>
                  <div>
                    <p className="text-[11px] font-semibold uppercase tracking-[0.25em] text-slate-400">{copy.basis}</p>
                    <p className="mt-2 rounded-xl bg-slate-50 p-4 text-sm leading-relaxed text-slate-700">{suggestion.legalBasis}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        <Separator className="bg-slate-200" />

        {result.agentArena?.arbitrationFindings?.length ? (
          <>
            <div className="px-10 py-8">
              <h2 className="text-lg font-bold">Arbitration Findings</h2>
              <div className="mt-5 flex flex-col gap-4">
                {result.agentArena.arbitrationFindings.map((finding, index) => (
                  <div key={`${finding.clauseRef}-${index}`} className="rounded-2xl border border-slate-200 p-5">
                    <div className="flex flex-wrap items-center gap-3">
                      <p className="text-sm font-bold">{finding.clauseRef}</p>
                      <span className="rounded-full bg-slate-100 px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-700">
                        {finding.verdict}
                      </span>
                      <span className="rounded-full bg-slate-900 px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.18em] text-white">
                        {finding.severity}
                      </span>
                    </div>
                    <p className="mt-3 text-sm font-semibold text-slate-900">{finding.finding}</p>
                    <p className="mt-2 text-sm leading-relaxed text-slate-700">{finding.rationale}</p>
                  </div>
                ))}
              </div>
            </div>

            <Separator className="bg-slate-200" />
          </>
        ) : null}

        {result.agentArena?.evidence?.length ? (
          <>
            <div className="px-10 py-8">
              <h2 className="text-lg font-bold">Evidence Base</h2>
              <p className="mt-3 text-sm leading-relaxed text-slate-600">{result.agentArena.retrievalSummary}</p>
              <div className="mt-5 flex flex-col gap-4">
                {result.agentArena.evidence.map((citation) => (
                  <div key={citation.id} className="rounded-2xl border border-slate-200 p-5">
                    <div className="flex flex-wrap items-center justify-between gap-3">
                      <div>
                        <p className="text-sm font-bold text-slate-900">{citation.title}</p>
                        <p className="mt-1 text-[11px] uppercase tracking-[0.2em] text-slate-500">
                          {citation.sourceType} / {citation.jurisdiction} / {citation.year}
                        </p>
                      </div>
                      <p className="text-xs font-medium text-slate-500">{citation.citation}</p>
                    </div>
                    <p className="mt-3 text-sm leading-relaxed text-slate-700">{citation.holding}</p>
                    <p className="mt-2 text-sm leading-relaxed text-slate-500">{citation.relevance}</p>
                  </div>
                ))}
              </div>
            </div>

            <Separator className="bg-slate-200" />
          </>
        ) : null}

        <div className="px-10 py-8">
          <h2 className="text-lg font-bold">{copy.checklist}</h2>
          <div className="mt-5 flex flex-col gap-3">
            {(result.checklist ?? []).map((item, index) => (
              <div key={`${item}-${index}`} className="flex items-start gap-3">
                <span className="mt-1 inline-block size-4 rounded-sm border border-slate-400" />
                <p className="text-sm leading-relaxed text-slate-700">{item}</p>
              </div>
            ))}
          </div>
        </div>

        <Separator className="bg-slate-200" />

        <div className="px-10 py-8">
          <p className="text-xs leading-relaxed text-slate-500">{copy.footer}</p>
        </div>
      </div>
    </div>,
    document.body
  );
}
